# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/chef/chef_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lib/chef/chef_data.proto',
  package='chef.data',
  serialized_pb='\n\x18lib/chef/chef_data.proto\x12\tchef.data\"1\n\x12VariableAssignment\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x0c\"H\n\x0fInputAssignment\x12\x35\n\x0evar_assignment\x18\x01 \x03(\x0b\x32\x1d.chef.data.VariableAssignment\"C\n\tForkPoint\x12\r\n\x05\x64\x65pth\x18\x01 \x01(\r\x12\x11\n\ttarget_pc\x18\x02 \x01(\x06\x12\x14\n\x0c\x62ranch_index\x18\x03 \x01(\r\"@\n\x11\x45xecutionDistance\x12\x15\n\rpath_distance\x18\x01 \x02(\r\x12\x14\n\x0c\x63\x66g_distance\x18\x02 \x02(\r\"\xd7\x02\n\x08TestCase\x12\x12\n\ntime_stamp\x18\n \x02(\x04\x12)\n\x05input\x18\x01 \x02(\x0b\x32\x1a.chef.data.InputAssignment\x12.\n\nseed_input\x18\t \x03(\x0b\x32\x1a.chef.data.InputAssignment\x12\x1a\n\x12high_level_path_id\x18\x08 \x01(\x04\x12(\n\nfork_point\x18\x07 \x03(\x0b\x32\x14.chef.data.ForkPoint\x12\x19\n\x11\x64ist_to_uncovered\x18\x0e \x01(\r\x12\x35\n\x0ftree_divergence\x18\x0c \x01(\x0b\x32\x1c.chef.data.ExecutionDistance\x12\x34\n\x0e\x63\x66g_divergence\x18\r \x01(\x0b\x32\x1c.chef.data.ExecutionDistance\x12\x0e\n\x06output\x18\x0b \x01(\x0c')




_VARIABLEASSIGNMENT = _descriptor.Descriptor(
  name='VariableAssignment',
  full_name='chef.data.VariableAssignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='chef.data.VariableAssignment.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='chef.data.VariableAssignment.value', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=88,
)


_INPUTASSIGNMENT = _descriptor.Descriptor(
  name='InputAssignment',
  full_name='chef.data.InputAssignment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='var_assignment', full_name='chef.data.InputAssignment.var_assignment', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=90,
  serialized_end=162,
)


_FORKPOINT = _descriptor.Descriptor(
  name='ForkPoint',
  full_name='chef.data.ForkPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='depth', full_name='chef.data.ForkPoint.depth', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_pc', full_name='chef.data.ForkPoint.target_pc', index=1,
      number=2, type=6, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='branch_index', full_name='chef.data.ForkPoint.branch_index', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=164,
  serialized_end=231,
)


_EXECUTIONDISTANCE = _descriptor.Descriptor(
  name='ExecutionDistance',
  full_name='chef.data.ExecutionDistance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path_distance', full_name='chef.data.ExecutionDistance.path_distance', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cfg_distance', full_name='chef.data.ExecutionDistance.cfg_distance', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=233,
  serialized_end=297,
)


_TESTCASE = _descriptor.Descriptor(
  name='TestCase',
  full_name='chef.data.TestCase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='chef.data.TestCase.time_stamp', index=0,
      number=10, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input', full_name='chef.data.TestCase.input', index=1,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seed_input', full_name='chef.data.TestCase.seed_input', index=2,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='high_level_path_id', full_name='chef.data.TestCase.high_level_path_id', index=3,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fork_point', full_name='chef.data.TestCase.fork_point', index=4,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dist_to_uncovered', full_name='chef.data.TestCase.dist_to_uncovered', index=5,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tree_divergence', full_name='chef.data.TestCase.tree_divergence', index=6,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cfg_divergence', full_name='chef.data.TestCase.cfg_divergence', index=7,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output', full_name='chef.data.TestCase.output', index=8,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=300,
  serialized_end=643,
)

_INPUTASSIGNMENT.fields_by_name['var_assignment'].message_type = _VARIABLEASSIGNMENT
_TESTCASE.fields_by_name['input'].message_type = _INPUTASSIGNMENT
_TESTCASE.fields_by_name['seed_input'].message_type = _INPUTASSIGNMENT
_TESTCASE.fields_by_name['fork_point'].message_type = _FORKPOINT
_TESTCASE.fields_by_name['tree_divergence'].message_type = _EXECUTIONDISTANCE
_TESTCASE.fields_by_name['cfg_divergence'].message_type = _EXECUTIONDISTANCE
DESCRIPTOR.message_types_by_name['VariableAssignment'] = _VARIABLEASSIGNMENT
DESCRIPTOR.message_types_by_name['InputAssignment'] = _INPUTASSIGNMENT
DESCRIPTOR.message_types_by_name['ForkPoint'] = _FORKPOINT
DESCRIPTOR.message_types_by_name['ExecutionDistance'] = _EXECUTIONDISTANCE
DESCRIPTOR.message_types_by_name['TestCase'] = _TESTCASE

class VariableAssignment(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _VARIABLEASSIGNMENT

  # @@protoc_insertion_point(class_scope:chef.data.VariableAssignment)

class InputAssignment(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INPUTASSIGNMENT

  # @@protoc_insertion_point(class_scope:chef.data.InputAssignment)

class ForkPoint(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FORKPOINT

  # @@protoc_insertion_point(class_scope:chef.data.ForkPoint)

class ExecutionDistance(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _EXECUTIONDISTANCE

  # @@protoc_insertion_point(class_scope:chef.data.ExecutionDistance)

class TestCase(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TESTCASE

  # @@protoc_insertion_point(class_scope:chef.data.TestCase)


# @@protoc_insertion_point(module_scope)
